specfile_path: p11-kit.spec
synced_files:
  - p11-kit.spec
  - .packit.yaml
upstream_package_name: p11-kit
downstream_package_name: p11-kit
actions:
   post-upstream-clone:
   - wget https://src.fedoraproject.org/rpms/p11-kit/raw/master/f/p11-kit.spec
   - wget https://src.fedoraproject.org/rpms/p11-kit/raw/master/f/p11-kit-client.service
   - wget https://src.fedoraproject.org/rpms/p11-kit/raw/master/f/trust-extract-compat
   - sed -i -e '/^Source[12]:/d' -e '/^gpgv2 /d' p11-kit.spec

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-development

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: fedora-all
