specfile_path: p11-kit.spec
upstream_package_name: p11-kit
downstream_package_name: p11-kit

# Use only populated spec files and upstream sources.
actions:
  post-upstream-clone:
    - wget https://src.fedoraproject.org/rpms/p11-kit/raw/rawhide/f/p11-kit.spec
    - wget https://src.fedoraproject.org/rpms/p11-kit/raw/rawhide/f/p11-kit-client.service
    - wget https://src.fedoraproject.org/rpms/p11-kit/raw/rawhide/f/trust-extract-compat
  get-current-version:
    - "git describe --abbrev=0"
  create-archive:
    - "wget https://github.com/p11-glue/p11-kit/releases/download/$PACKIT_PROJECT_VERSION/p11-kit-$PACKIT_PROJECT_VERSION.tar.xz"
    - "wget https://github.com/p11-glue/p11-kit/releases/download/$PACKIT_PROJECT_VERSION/p11-kit-$PACKIT_PROJECT_VERSION.tar.xz.sig"

jobs:
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches: fedora-all
