matrix:
  include:
    - os: freebsd

language: c

before_install:
  - |
      if test -e "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/before_install.sh"; then
        . "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/before_install.sh"
      fi

install:
  - |
      if test -e "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/install.sh"; then
        . "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/install.sh"
      fi

script:
  - |
      if test -e "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/script.sh"; then
        . "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/script.sh"
      fi

after_failure:
  - |
      if test -e "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/after_failure.sh"; then
        . "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/after_failure.sh"
      fi

after_success:
  - |
      if test -e "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/after_success.sh"; then
        . "./.travis/${PROFILE-${TRAVIS_OS_NAME}}/after_success.sh"
      fi
